feat: set image for android notification
lkaybob/php-fcm-v1 pull request #19
Opened 2023-11-02 03:11 UTC by mgcastelberg

### Goal
Send image on android notification

- Add setImage for android notification
- Add testSetImage unit tests and integration test

2023-11-05 09:01 UTC, lkaybob commented
Guess there's something wrong with GitHub Actions. I'll look into it and make sure the action runs properly.

2023-11-07 23:39 UTC, mgcastelberg commented
OK, thank you very much for reviewing my contribution, I hope the part of the github actions is resolved soon, once you tell me that everything is in order, I will upload the second part to send images for IOS

Have a great night.

        Atte. Ing. José Manuel Gómez Castelberg
Diseñador / Programador
We Play Code  S. A.  de C. V.
Jugamos código

________________________________
De: Sunghyuk Kay ***@***.***>
Enviado: domingo, 5 de noviembre de 2023 02:01 a. m.
Para: lkaybob/php-fcm-v1 ***@***.***>
Cc: Manuel Gómez ***@***.***>; Author ***@***.***>
Asunto: Re: [lkaybob/php-fcm-v1] feat: set image for android notification (PR #19)


Guess there's something wrong with GitHub Actions. I'll look into it and make sure the action runs properly.

—
Reply to this email directly, view it on GitHub<https://github.com/lkaybob/php-fcm-v1/pull/19#issuecomment-1793666965>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACFAT3LQF63ZTOKD2OPF5LTYC5BWBAVCNFSM6AAAAAA62GYXHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJTGY3DMOJWGU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-11-12 09:01 UTC, lkaybob commented
@mgcastelberg Sorry for the delay. I guess I found the issue.

In Github Actions, there is a step that decrypts encrypted service account file(`service_account.json.gpg`), which requires repository secret. Github Actions does allow repository secrets to be shared with forked repository for specific event(`pull_request_target`), but it requires [Github Actions manifest file](https://github.com/lkaybob/php-fcm-v1/blob/master/.github/workflows/main.yml) to be updated.

So I guess there should be two options so far.

**Option 1) Rebasing merge request.**
I update the GA manifest file on master branch first, and then you rebase your working branch to updated master branch. This method is canonical way to do in my opinion. Although it requires few tricky local git commands on both sides, this would definitely make sure that GA works fine.

**Option 2) Temporarily set secret on your side**
As a workaround other than first option, I can share you the secret, and you set it on your forked repository. This one does not require git interactions, but I'm not sure this method would work, but at least we can try.

If option 2 works, I will update encrypted service account file with different passphrase and GA manifest file, so that you can work on iOS part. (Of course, if option 2 does not work, we should stick to first options :( )

Please let me know which do you prefer.

2023-11-12 23:43 UTC, mgcastelberg commented
Hello lkaybob, if you like, we will try the easiest way, which is option 2, and if this definitely does not work, we will use the other alternative.Likewise, if you consider that option 1 is safer and guarantees greater certainty, we can try it, I would just need your help to see what steps I should take.Thank you in advance for following up on my participation, I am very happy to be learning new things with Git and collaborating with you.



        Atte. Ing. José Manuel Gómez Castelberg
Diseñador / Programador
We Play Code  S. A.  de C. V.
Jugamos código

________________________________
De: Sunghyuk Kay ***@***.***>
Enviado: domingo, 12 de noviembre de 2023 03:01 a. m.
Para: lkaybob/php-fcm-v1 ***@***.***>
Cc: Manuel Gómez ***@***.***>; Mention ***@***.***>
Asunto: Re: [lkaybob/php-fcm-v1] feat: set image for android notification (PR #19)


@mgcastelberg<https://github.com/mgcastelberg> Sorry for the delay. I guess I found the issue.

In Github Actions, there is a step that decrypts encrypted service account file(service_account.json.gpg), which requires repository secret. Github Actions does allow repository secrets to be shared with forked repository for specific event(pull_request_target), but it requires Github Actions manifest file<https://github.com/lkaybob/php-fcm-v1/blob/master/.github/workflows/main.yml> to be updated.

So I guess there should be two options so far.

Option 1) Rebasing merge request.
I update the GA manifest file on master branch first, and then you rebase your working branch to updated master branch. This method is canonical way to do in my opinion. Although it requires few tricky local git commands on both sides, this would definitely make sure that GA works fine.

Option 2) Temporarily set secret on your side
As a workaround other than first option, I can share you the secret, and you set it on your forked repository. This one does not require git interactions, but I'm not sure this method would work, but at least we can try.

If option 2 works, I will update encrypted service account file with different passphrase and GA manifest file, so that you can work on iOS part. (Of course, if option 2 does not work, we should stick to first options :( )

Please let me know which do you prefer.

—
Reply to this email directly, view it on GitHub<https://github.com/lkaybob/php-fcm-v1/pull/19#issuecomment-1807062520>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACFAT3LCTH7VCXWWVGSXVD3YECGANAVCNFSM6AAAAAA62GYXHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBXGA3DENJSGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-14 01:08 UTC, lkaybob commented
Thank you for your understanding. Let's try second option first.

Could you send me an email to hello@lkaybob.pe.kr? (Since I can't see email address on your Github profile)

After you sending me an email, I will reply with passphrase and a guide to set secret on forked reository.

2023-11-14 03:23 UTC, mgcastelberg commented
Hello Sunghyuk Kay

I already sent you my email from my personal account

Greetings



        Atte. Ing. José Manuel Gómez Castelberg
Diseñador / Programador
We Play Code  S. A.  de C. V.
Jugamos código


________________________________
De: Sunghyuk Kay ***@***.***>
Enviado: lunes, 13 de noviembre de 2023 07:09 p. m.
Para: lkaybob/php-fcm-v1 ***@***.***>
Cc: Manuel Gómez ***@***.***>; Mention ***@***.***>
Asunto: Re: [lkaybob/php-fcm-v1] feat: set image for android notification (PR #19)


Thank you for your understanding. Let's try second option first.

Could you send me an email to ***@***.******@***.***>? (Since I can't see email address on your Github profile)

After you sending me an email, I will reply with passphrase and a guide to set secret on forked reository.

—
Reply to this email directly, view it on GitHub<https://github.com/lkaybob/php-fcm-v1/pull/19#issuecomment-1809381426>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACFAT3KNKOMLMGTLYHTKLHLYELADJAVCNFSM6AAAAAA62GYXHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBZGM4DCNBSGY>.
You are receiving this because you were mentioned.

2023-11-22 13:34 UTC, lkaybob commented
@mgcastelberg Sorry for the delay. I was busy for a while, and I've done some research on first option that I suggested, since second option didn't go well.

It seems Github Actions does not work as I understood, so restoring GA workflow would need additional administrative actions. (ex. Changing mechanism to test library with actual service account.)

I will assume your code runs well, so let's merge after my review.

2023-11-22 13:40 UTC, lkaybob requested changes
Feel free to leave your opinion on the review.

2023-11-29 09:09 UTC, mgcastelberg reviewed
Once approved, I will perform a couple of tests from my project to verify that everything is in order.

2023-11-29 09:09 UTC, mgcastelberg commented on .gitignore
> +composer.lock
Well it seems that everything is in order, without problem you can remove the composer.lock from git.ignore

thank you @lkaybob

2023-11-30 07:25 UTC, merged

2023-11-30 07:30 UTC, lkaybob commented
Thank you for your contribution. @mgcastelberg 

I'm planning to create a release after your next contribution, since you are planning to add image send support for iOS. If you want to test the merged code so far, I guess you have to specify your project's composer to get package from master branch.

FYI. Tests ran successfully after the merge.
https://github.com/lkaybob/php-fcm-v1/actions/runs/7043311400/job/19168864687